# -*- coding: utf-8 -*-
"""
/***************************************************************************
Geometric features
                                 A QGIS plugin
 Zonal statistics from polygon
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-03-14
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Luis Fernando Chimelo Ruiz
        email                : ruiz.ch@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QObject, pyqtSignal,QVariant
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from qgis.core import *
import numpy as np
import os
import sys
import processing
import time
import math
#To evaluate
from .to_evaluate import list_is_empty, exist_file, is_defined,is_crs
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .geometrics_dialog import GeometricDialog
import os.path


class Geometric:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'geometric_feature_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlg = GeometricDialog()

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GeoPatterns')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'Geometric features')
        self.toolbar.setObjectName(u'Geometric features')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Geometric features', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/geometric_features/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Geometric features'),
            callback=self.run,
            parent=self.iface.mainWindow())


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Geometric features'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar
        #disconnect        

        return 0
    
    def run(self):
        """Run method that performs all the real work"""
        #try disconnect
        try:
            self.dlg.ui.buttonInVec.clicked.disconnect(self.set_path_vectors)
            self.dlg.ui.buttonExit.clicked.disconnect(self.cancel_GUI)
            self.dlg.ui.buttonRun.clicked.disconnect(self.run_geometrics)
        except:
            pass
        #Clear GUI
        self.dlg.ui.lineEditVec.clear()
        self.dlg.ui.textEditOut.clear()
        #Zero  progress bar
        self.dlg.ui.progressBar.setValue(0)
        
        #Connect functions
        self.dlg.ui.buttonInVec.clicked.connect(self.set_path_vectors)
        self.dlg.ui.buttonExit.clicked.connect(self.cancel_GUI)
        self.dlg.ui.buttonRun.clicked.connect(self.run_geometrics)           
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
        
    
    def set_path_vectors(self):
        #Open Directory
        self.pathVecs = QFileDialog.getExistingDirectory(None, self.tr('Open a folder'), None, QFileDialog.ShowDirsOnly)  
        #Set lineEditPathSegs
        self.dlg.ui.lineEditVec.setText(self.pathVecs)
        return 0
    
    def cancel_GUI(self):
        #disconnect        

        self.dlg.ui.buttonInVec.clicked.disconnect(self.set_path_vectors)
        self.dlg.ui.buttonExit.clicked.disconnect(self.cancel_GUI)
        self.dlg.ui.buttonRun.clicked.disconnect(self.run_geometrics)
        
        self.dlg.close()
        return 0
    
    def run_geometrics (self):

        #Get lineEditInVec - Input vectors path        
        if is_defined(self.dlg.ui.lineEditVec.text(),"Input: Undefined vectors path"):
            return 0 
        
        else:
           
            #Get statistics
            geom_feats=[]
            fields_names=[]
            if self.dlg.ui.checkBoxArea.checkState():
                #Append geometrics feature
                geom_feats.append(QgsField('area_ha', QVariant.Double, 'double', 15, 4))
                fields_names.append('area_ha')
            if self.dlg.ui.checkBoxRoud.checkState():
                #Append geometrics feature
                geom_feats.append(QgsField('roundness', QVariant.Double, 'double', 10, 2))
                fields_names.append('roundness')
            if self.dlg.ui.checkBoxPerimet.checkState():
                #Append geometrics feature
                geom_feats.append(QgsField('perimeter', QVariant.Double, 'double', 12, 2))
                fields_names.append('perimeter')
            if self.dlg.ui.checkBoxFatCirc.checkState():
                #Append geometrics feature
                geom_feats.append(QgsField('circ_fact', QVariant.Double, 'double', 10, 2))
                fields_names.append('circ_fact')
            if self.dlg.ui.checkBoxCompact.checkState():
                #Append geometrics feature
                geom_feats.append(QgsField('compact', QVariant.Double, 'double', 10, 2))
                fields_names.append('compact')
            if self.dlg.ui.checkBoxSoft.checkState():
                #Append geometrics feature
                geom_feats.append(QgsField('softness', QVariant.Double, 'double', 10, 2))
                fields_names.append('softness')
            if self.dlg.ui.checkBoxRet.checkState():
                #Append statistics
                geom_feats.append(QgsField('rectang', QVariant.Double, 'double', 10, 2))
                fields_names.append('rectang')

            #stattistics 
            if list_is_empty(geom_feats,"Parameters: Select Geometrics Feature"):
                return 0 
            #Set lineEdit Out
            self.dlg.ui.textEditOut.setText('Geometrics features')

           
            #Get files paths
            vectors_path=self.dlg.ui.lineEditVec.text()
            #Assess path
            if exist_file(vectors_path,'Input: vectors path is not exist'):
                    return 0
            else:
                    pass
            #Read vectors files
            vectors_files=[vectors_path+os.sep+file for file in os.listdir(vectors_path) if file.endswith(".shp") ]
            #vectors files   
            if list_is_empty(vectors_files,"Input: There isn't vectors (Vectors path: .shp)"):
                return 0 
            
            else:
                pass

            #ASsess vectors file exist
            for vc in vectors_files:
                #Read vector
                vector = QgsVectorLayer(vc, 'vector', 'ogr')
                #Assess read file
                if  not vector.isValid():
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Information)
                    msg.setText("Error read layer: "+vc)
                    msg.setWindowTitle("Info")
                    msg.exec_() 
                    return 0
                else:
                    pass
            #somar loop
            count=1
            #set value progressBar
            self.dlg.ui.progressBar.setValue(1.0)
            totale = len(vectors_files)
            #Loop about vectors_files
            for vec in vectors_files:
                #Ler shapefile
                layer=QgsVectorLayer(vec, 'shape', 'ogr')
                #Avaliar as capacidades do provedor
                caps = layer.dataProvider().capabilities()
                #Inserir campo na tabela
                if caps & QgsVectorDataProvider.AddAttributes:
                    res = layer.dataProvider().addAttributes(geom_feats)
                else:
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Information)
                    msg.setText("Error create geometrics feature: "+vc)
                    msg.setWindowTitle("Info")
                    msg.exec_() 
                    return 0
                
                #Atualizar layer
                layer.updateFields()
                #Obter os registros
                features = layer.getFeatures()
                #Start editing
                layer.startEditing()
                # nLoop sobre os registros
                for feat in features:
                    #Obter as geoemtrias
                    geom = feat.geometry()
                    #Calcular area
                    area=geom.area()
                    #length
                    length=geom.length()
                    #Convex hull
                    #convex_length=geom.convexHull().length()
                    #Circle
                    circle=geom.minimalEnclosingCircle()
                    #area_circ=circle[0].area()
                    #len_circ=circle[0].length()
                    radius_circ=circle[2]
                    #Bounding box oriented
                    orientMinBBox = geom.orientedMinimumBoundingBox()
                    area_bbox_orient = orientMinBBox[1] 
                    len_bbox_orient = orientMinBBox[0].length() 
                    geometrics_calcs={'area_ha':area/10000,'perimeter':length,'compact':length/(area)**0.5,'softness':length/len_bbox_orient,'rectang':area_bbox_orient/area,'roundness':(math.pi*(2*radius_circ)**2)/(4*area),'circ_fact':(length**2)/(4*area*math.pi)}
                    #Inserir valor no campo da tabela
                    [feat.setAttribute(field,geometrics_calcs[field]) for field in fields_names]   
                        
                    #Atualizar modificacoes
                    layer.updateFeature(feat)
                #Enviar modificacoes
                layer.commitChanges()
                #Deletar layer
                del(layer)
                #Set lineEdi Out
                self.dlg.ui.textEditOut.append(vec)
                #set value progressBar
                self.dlg.ui.progressBar.setValue((float(count)/totale)*100)
                count+=1
            #set 100 progressaBar
            self.dlg.ui.progressBar.setValue(100)
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Finish")
            msg.setWindowTitle("Info")
            msg.exec_() 
            return 0